name: Super Linter
on:
  push:
    branches: [ main]
    paths:
    - '**.tf'
    - '**.json'
  pull_request:
    branches: [ main ]
    paths:
    - '**.tf'
    - '**.json'
  schedule:
  - cron: "0 0 * * *" #at the end of every day
  workflow_dispatch:

jobs:
  build:
    name: Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Super Linter
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_TERRAFORM: true
          VALIDATE_TERRAFORM_TERRASCAN: true
          VALIDATE_JSON: true
