name: Terraform-Tests
on:
  push:
    branches: [ main ]
    paths:
    - '**.tf'
  pull_request:
    branches: [ main ]
    paths:
    - '**.tf'
  schedule:
  - cron: "0 0 * * *" #at the end of every day
  workflow_dispatch:
    
jobs:

  Terraform-ValidationTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Validate Terraform
      uses: docker://ghcr.io/github/super-linter:slim-v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        VALIDATE_TERRAFORM: true
        VALIDATE_TERRAFORM_TERRASCAN: true

  Terraform-CD:
    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
    needs: Terraform-ValidationTests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEVTEST }}
    - uses: hashicorp/setup-terraform@v1.2.1
      with:
        cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
        terraform_version: 0.13.4
      
    - name: Terraform Init
      id: init
      run: terraform init -backend-config=backend.hcl -no-color
      working-directory: Terraform

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -no-color
      working-directory: Terraform

    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -auto-approve -no-color
      working-directory: Terraform
